### ISSUE TITLE
Bot is not clicking the "Auto" button after attacking

### ISSUE THREAD

**Issue by einhazard** [steve1316/granblue-automation-android#29] opened 2022-09-30 12:32 UTC
Not sure why, I just click start and open skyleap, all works fine and it even click the "Attack" Button but not the "Auto" button
but the Overlay color still red so if I finish the battling myself it will try to replay the battle

EDIT:
I'm using bluestack 5 in case you wondering

![image](https://user-images.githubusercontent.com/56389771/193270366-1f2a7f1e-96eb-4dba-b080-4292f0403d8f.png)

**Comment by steve1316** [comment] 2022-10-04 01:51
Can you retry on the newest version, v3.8.1? Tried to reproduce your issue but the bot always hit the Full Auto after all commands were executed.

**Comment by einhazard** [comment] 2022-10-04 11:42
as for the click the auto button, it works now, thanks

but, for some reason the bot now never success to get the right party slot

I'm using Group #7, and Party #2 in the setting. the bot success to get the same group, but for some reason it will always choose party #1.
But at least I can workaround this by clicking the party #2 ,manually then the bot will do the rest.

do I need to change some resolution in bluestack or browser setting?

maybe you want to check that out, but there is no error in the log
![image](https://user-images.githubusercontent.com/56389771/193809153-cd8d72fc-275e-4c30-b7b5-f45bb3d86972.png)


After 1 or 2 repeated run, for some reason it refreshing during loot collection so the windows stuck on this screen
![image](https://user-images.githubusercontent.com/56389771/193810737-321a7752-aabe-4de7-ae5e-13abc126b6f7.png)

here the last log:
![image](https://user-images.githubusercontent.com/56389771/193810873-14ee88ab-5ccb-49d3-90cf-4c0dcf646b8b.png)

**Comment by steve1316** [comment] 2023-01-04 02:48
Since v3.9.0 introduced a lot of changes, including to Combat Mode, closing this issue for now as it is probably addressed in those changes. If you encounter this issue again, feel free to reopen this or open a new issue.

**Closed by steve1316** 2023-01-04 02:48 UTC
