### ISSUE TITLE
Button not found

### ISSUE THREAD

**Issue by kevin01523** [steve1316/granblue-automation-android#5] opened 2021-08-26 05:27 UTC
It seems it has troubled finding some buttons like full auto but it works with semi on normal special quest like deluge trial

![Screenshot_20210826-131510](https://user-images.githubusercontent.com/8380242/130905743-e6d1fbda-41b1-4122-bc0e-9507a6a84739.jpg)
![Screenshot_20210826-132537](https://user-images.githubusercontent.com/8380242/130905825-10c00ef3-3a91-405c-9132-be9199257001.jpg)

I'm on android 10
I'm using skyleap browser 
I tried both standard and lite graphical settings

I'll try on chrome later

**Comment by steve1316** [comment] 2021-08-28 00:15
For the Tab S7, it would only work in a split screen configuration with the browser on the left side, and Desktop Mode turned off for portrait and turned on for landscape. And even then, it would often get stuck so Tab S7 support remains experimental for now.

I will get around to creating a setting soon that will allow you to adjust the confidence that the OCR determines to be a match. Currently it is set to be at least 80% or more.

**Comment by kevin01523** [comment] 2021-08-31 18:09
i guess an option to add own images would be nice where the app would read from
which coild be enabled as a debug feature  eith a toggle also a log export would be nice
i experience lots of java errors like outof bounds but i cant see the error details as the apps do crash.

npnp take your time

**Comment by steve1316** [comment] 2021-09-03 20:28
Just updated the bot to v2.5.0. Added 2 new options for setting the confidence levels for both single and multi match CV operations. Could not implement the option to replace images with your own without a significant overhaul of the bot. 

I might come back to this later so hopefully setting your own confidence levels will solve your incompatibility issue. Let me know how it goes!

**Comment by steve1316** [comment] 2021-09-03 21:09
Forgot to mention, logs are saved in the /logs/ folder in the application folder inside your internal storage's /Android/data/.

However, logs do not print the segfault errors. These ones causes the app to crash completely and leaves no stacktrace, which makes it so that I cannot find what is the cause. They typically happen when you stop the bot while it is in the middle of doing something like searching for summons and even then, it segfaults at random.

**Comment by kevin01523** [comment] 2021-09-04 03:13
OK I'll test it for a few hours to few days I'll updatebyoubon my findings

**Comment by kevin01523** [comment] 2021-09-04 04:06
Seems that it manages to find the full auto button now if I set both confidence to 70. I haven't tested it on other quest except deluge trial.I also noticed it has no recovery in the event it got stuck during the quest I guess doing a reload for recovery is helpful

**Comment by steve1316** [comment] 2021-09-04 04:21
By recovery, do you mean AP/EP recovery? If so, turn on all 3 of these settings in the Misc section:

![chrome_XzMgrD9m87](https://user-images.githubusercontent.com/18709555/132082183-30a602af-737e-45af-a8fa-445ada7f842a.png)

and then enable this in the Settings page of the bot:

![studio64_HMuF4p3PIQ](https://user-images.githubusercontent.com/18709555/132082221-a3eac656-7c86-4968-9ccf-4dcb75702a43.png)

**Comment by steve1316** [comment] 2021-09-05 21:48
Just updated the bot to v2.5.1 and included a new setting that will allow you to set your own image scale. You can find out your scale by taking a screenshot directly on your device and then pick a easily recognizable image asset from the /images/folder in this repository and scaling it until it relatively matches the size of the asset in your screenshot. Whatever percentage you scaled the image asset by will be the number that will go into this new setting.

Let me know how it goes!

**Comment by kevin01523** [comment] 2021-09-06 01:11
Ah what I meant for recovery is when the game itself get stuck while loading due to connection issues the not can click the reload button to recover(well that's a diff issue altogether) ill test the new version it later

**Comment by steve1316** [comment] 2021-09-06 01:29
Ah, sorry about that. It is at app/src/main/assets/buttons/ in this GitHub repository.

I may consider adding an option to have the bot reload the page if it doesn't arrive at the correct location but I will need to think more on it.

**Comment by kevin01523** [comment] 2021-09-07 16:08
![Screenshot_20210907-235235](https://user-images.githubusercontent.com/8380242/132376645-0e68ce33-f282-4a73-8fd0-b371c1babdaf.jpg)
![Screenshot_20210908-000518](https://user-images.githubusercontent.com/8380242/132376705-96a77b34-76f9-4bc8-81d9-aec8f02945eb.jpg)
![Screenshot_20210908-000533](https://user-images.githubusercontent.com/8380242/132376725-3c8d70d6-9401-439c-9505-e48fa030111b.jpg)
i guess still can't find full auto at confidence 80 
also its stops if the test for home screen is enabled?

**Comment by steve1316** [comment] 2021-09-07 16:12
It does not conduct the next text if the current scale/confidence settings already found the Home screen. It needs to fail that first before doing the test to find a scale that works for you. You can force it to do that by setting your scale something low like 0.20.

When it can't find the full auto button, is it already at the Combat screen?

In addition, you can find the latest logs with all of these logging messages in the /logs/ folder under the /Android/data/ folder in your internal storage.

**Comment by kevin01523** [comment] 2021-09-07 20:20
it fails to find the full auto if confidence is 77-100 but finds it on 70 i guess ill test again

**Comment by steve1316** [comment] 2021-09-07 20:35
Oh my bad, I did not realize you had 1080p screen. The bot supports 1080p by default but it accidentally sees your device as not having 1080p screen. This will be fixed in next update later today in v2.5.3.

**Comment by kevin01523** [comment] 2021-09-07 21:04
> Oh my bad, I did not realize you had 1080p screen. The bot supports 1080p by default but it accidentally sees your device as not having 1080p screen. This will be fixed in next update later today in v2.5.3.

i did mention it on the previous comments oh well i hope  it does get fixed

**Comment by kevin01523** [comment] 2021-09-08 14:08
![Screenshot_20210908-220140](https://user-images.githubusercontent.com/8380242/132524672-f4f5a5c2-d298-4dfa-9657-26f65eb98bc2.jpg)
![Screenshot_20210908-220314](https://user-images.githubusercontent.com/8380242/132524690-e3014fcf-1629-41d8-b75a-d7898eee8451.jpg)



I guess at scale 1.0 and confidence 80 it still cannot find full auto atleast less crashes now and can find quest buttons etc

**Comment by kevin01523** [comment] 2021-09-08 14:39
More logs
It didn't push the attack button dunno why

**Closed** 2021-10-07 04:20 UTC
Labels: bug, enhancement
